version: "3"
services:
  worker-download:
    environment:
      - PYTHONUNBUFFERED=1
    image: worker-download
    volumes:
      - video-dir:/youtube-audio:rw
    depends_on:
      - redis
      - kafka
  worker-recognize:
    environment:
      - PYTHONUNBUFFERED=1
    image: worker-recognize
    volumes:
      - video-dir:/youtube-audio:rw
    depends_on:
      - redis
      - kafka
  youtube2wav:
    environment:
      - PYTHONUNBUFFERED=1
    image: youtube2wav
    volumes:
      - video-dir:/youtube-audio:rw
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
      - worker-download
  voice-recognition:
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    image: voice-recognition
    depends_on:
      - redis
      - kafka
      - youtube2wav
      - worker-recognize
    ports:
      - "8090:8080"
  redis:
    image: redis:alpine3.12
    volumes:
      - redis_data:/data
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    volumes:
      - zookeeper_data:/bitnami/zookeeper:rw
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    volumes:
      - kafka_data:/bitnami/kafka:rw
    ports:
      - '9092:9092'
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
  kafka_data:
  redis_data:
  video-dir: