version: "3"
services:
  youtube2wav:
    environment:
      - PYTHONUNBUFFERED=1
    image: youtube2wav
    ports:
      - "8080:8080"
  voice-recognition:
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    image: voice-recognition
    depends_on:
      - redis
      - kafka
      - youtube2wav
    ports:
      - "8090:8080"
  redis:
    image: redis:alpine3.12
    volumes:
      - redis_data:/data
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
volumes:  
  redis_data: